In [100]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [101]:
df=pd.read_csv('cardekho.csv')
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [102]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  str
 2   brand              15411 non-null  str
 3   model              15411 non-null  str
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  str
 7   fuel_type          15411 non-null  str
 8   transmission_type  15411 non-null  str
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), str(6)
memory usage: 1.6 MB

In [103]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  str
 1   brand              15411 non-null  str
 2   model              15411 non-null  str
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  str
 6   fuel_type          15411 non-null  str
 7   transmission_type  15411 non-null  str
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), str(6)
memory usage: 1.5 MB

In [105]:
df['seller_type'].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [106]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [107]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [108]:
X=df.drop(columns=['selling_price'])
Y=df['selling_price']

In [109]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [110]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [111]:
encoding_list=['seller_type','transmission_type','fuel_type','brand','model']

X_train_encoded=encoder.fit_transform(X_train[encoding_list])
df_encoded=pd.DataFrame(X_train_encoded,columns=encoder.get_feature_names_out(encoding_list),index=X_train.index)
X_train=pd.concat([X_train.drop(columns=encoding_list),df_encoded],axis=1)

X_test_encoded=encoder.transform(X_test[encoding_list])
df_encoded_test=pd.DataFrame(X_test_encoded,columns=encoder.get_feature_names_out(encoding_list),index=X_test.index)
X_test=pd.concat([X_test.drop(columns=encoding_list),df_encoded_test],axis=1)

In [112]:
X_train.drop(columns=['car_name'], inplace=True)
X_test.drop(columns=['car_name'], inplace=True)

In [113]:
X_train.head()

,vehicle_age,km_driven,mileage,engine,max_power,seats,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_type_Automatic,...,model_XE,model_XF,model_XL6,model_XUV300,model_XUV500,model_Yaris,model_Z4,model_i10,model_i20,model_redi-GO
1079,8,98813,22.77,1498,98.59,5,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10368,12,65344,17.00,1497,118.00,5,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3730,4,30000,20.89,1197,81.80,5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13647,4,57000,13.68,2393,147.80,7,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4712,12,15000,13.60,2523,63.00,7,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [114]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 10787 entries, 1079 to 1289
Columns: 164 entries, vehicle_age to model_redi-GO
dtypes: float64(160), int64(4)
memory usage: 13.6 MB

In [115]:
X_train.head()

,vehicle_age,km_driven,mileage,engine,max_power,seats,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_type_Automatic,...,model_XE,model_XF,model_XL6,model_XUV300,model_XUV500,model_Yaris,model_Z4,model_i10,model_i20,model_redi-GO
1079,8,98813,22.77,1498,98.59,5,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10368,12,65344,17.00,1497,118.00,5,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3730,4,30000,20.89,1197,81.80,5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13647,4,57000,13.68,2393,147.80,7,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4712,12,15000,13.60,2523,63.00,7,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Model Training

In [131]:
params = {
    'n_estimators': [100, 200,300],
    'max_depth': [5,10,15],
    'min_samples_split': [5,10,20],
    'min_samples_leaf': [2,5,10]
}

In [132]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(random_state=42)
grid=GridSearchCV(estimator=rf,param_grid=params,cv=5,  scoring='neg_mean_squared_error',n_jobs=-1)

In [ ]:
grid.fit(X_train, Y_train)

In [127]:
y_train_pred = grid.best_estimator_.predict(X_train)

In [128]:
y_test_pred = grid.best_estimator_.predict(X_test)

In [129]:
print("Test MSE:", mean_squared_error(Y_test, y_test_pred))
print("Test RMSE:", np.sqrt(mean_squared_error(Y_test, y_test_pred)))
print("Test R2:", r2_score(Y_test, y_test_pred))

Test MSE: 232309197521.9555
Test RMSE: 481984.6444877217
Test R2: 0.7806145934872616

In [130]:
y_train_pred = grid.best_estimator_.predict(X_train)

print("Train R2:", r2_score(Y_train, y_train_pred))
print("Test R2:", r2_score(Y_test, y_pred))

Train R2: 0.9863482619723931
Test R2: 0.7806145934872616