<a href="https://colab.research.google.com/github/Gayathri7841/AI-Learning-Journey/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1) Import Packages**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

# **2) Load Dataset**

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving melb_data.csv to melb_data (1).csv

In [ ]:
df=pd.read_csv('melb_data.csv')
print(df.shape)
df.head()

(13580, 21)

       Suburb           Address  ...             Regionname Propertycount
0  Abbotsford      85 Turner St  ...  Northern Metropolitan        4019.0
1  Abbotsford   25 Bloomburg St  ...  Northern Metropolitan        4019.0
2  Abbotsford      5 Charles St  ...  Northern Metropolitan        4019.0
3  Abbotsford  40 Federation La  ...  Northern Metropolitan        4019.0
4  Abbotsford       55a Park St  ...  Northern Metropolitan        4019.0

[5 rows x 21 columns]

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

# **3) Inspection**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [ ]:
df.describe()

              Rooms         Price  ...    Longtitude  Propertycount
count  13580.000000  1.358000e+04  ...  13580.000000   13580.000000
mean       2.937997  1.075684e+06  ...    144.995216    7454.417378
std        0.955748  6.393107e+05  ...      0.103916    4378.581772
min        1.000000  8.500000e+04  ...    144.431810     249.000000
25%        2.000000  6.500000e+05  ...    144.929600    4380.000000
50%        3.000000  9.030000e+05  ...    145.000100    6555.000000
75%        3.000000  1.330000e+06  ...    145.058305   10331.000000
max       10.000000  9.000000e+06  ...    145.526350   21650.000000

[8 rows x 13 columns]

# **4)** **Define Target and features**

In [ ]:
y=df['Price']
x=df.drop(columns=['Price'])

In [ ]:
y

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...
13575    1245000.0
13576    1031000.0
13577    1170000.0
13578    2500000.0
13579    1285000.0
Name: Price, Length: 13580, dtype: float64

In [ ]:
x

              Suburb  ... Propertycount
0         Abbotsford  ...        4019.0
1         Abbotsford  ...        4019.0
2         Abbotsford  ...        4019.0
3         Abbotsford  ...        4019.0
4         Abbotsford  ...        4019.0
...              ...  ...           ...
13575  Wheelers Hill  ...        7392.0
13576   Williamstown  ...        6380.0
13577   Williamstown  ...        6380.0
13578   Williamstown  ...        6380.0
13579     Yarraville  ...        6543.0

[13580 rows x 20 columns]

In [ ]:
x.drop(columns=['Lattitude','Longtitude'],axis=1,inplace=True)

In [ ]:
x.columns

Index(['Suburb', 'Rooms', 'Type', 'Method', 'Date', 'Distance', 'Postcode',
       'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt',
       'CouncilArea', 'Regionname'],
      dtype='object')

# **5)Feature Engineering**

In [ ]:
x['Date']=pd.to_datetime(x['Date'],errors='coerce',dayfirst=True)
x['SoldYear']=  x['Date'].dt.year
x['SoldMonth']=  x['Date'].dt.month
x['SoldDate']=  x['Date'].dt.day
x.drop(columns=['Date'],axis=1,inplace=True)
x.head(3)

       Suburb  Rooms Type  ... SoldYear  SoldMonth  SoldDate
0  Abbotsford      2    h  ...     2016         12         3
1  Abbotsford      2    h  ...     2016          2         4
2  Abbotsford      3    h  ...     2017          3         4

[3 rows x 17 columns]

# **6)Seperate Numerical and Categorical data**

In [ ]:
num=x.select_dtypes(include="number")
cat=x.select_dtypes(exclude="number")

In [ ]:
num

       Rooms  Distance  Postcode  ...  SoldYear  SoldMonth  SoldDate
0          2       2.5    3067.0  ...      2016         12         3
1          2       2.5    3067.0  ...      2016          2         4
2          3       2.5    3067.0  ...      2017          3         4
3          3       2.5    3067.0  ...      2017          3         4
4          4       2.5    3067.0  ...      2016          6         4
...      ...       ...       ...  ...       ...        ...       ...
13575      4      16.7    3150.0  ...      2017          8        26
13576      3       6.8    3016.0  ...      2017          8        26
13577      3       6.8    3016.0  ...      2017          8        26
13578      4       6.8    3016.0  ...      2017          8        26
13579      4       6.3    3013.0  ...      2017          8        26

[13580 rows x 12 columns]

In [ ]:
cat

              Suburb Type Method CouncilArea                  Regionname
0         Abbotsford    h      S       Yarra       Northern Metropolitan
1         Abbotsford    h      S       Yarra       Northern Metropolitan
2         Abbotsford    h     SP       Yarra       Northern Metropolitan
3         Abbotsford    h     PI       Yarra       Northern Metropolitan
4         Abbotsford    h     VB       Yarra       Northern Metropolitan
...              ...  ...    ...         ...                         ...
13575  Wheelers Hill    h      S         NaN  South-Eastern Metropolitan
13576   Williamstown    h     SP         NaN        Western Metropolitan
13577   Williamstown    h      S         NaN        Western Metropolitan
13578   Williamstown    h     PI         NaN        Western Metropolitan
13579     Yarraville    h     SP         NaN        Western Metropolitan

[13580 rows x 5 columns]

# **7) Preprocessing Pipeline(impute +encode + scaling)**

In [ ]:
#numeric value-median impute + scale
num_transformation=Pipeline(steps=[("imputer",SimpleImputer(strategy="median")),
                ("scaling",StandardScaler())])
#categorical :most frequent+one hot encodeing
cat_transformtion=Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),
                ("onehot",OneHotEncoder(handle_unknown='ignore'))])
preprocessor=ColumnTransformer(transformers=[("num",num_transformation,num),("cat",cat_transformtion,cat)],
                  remainder="drop")
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                        Rooms  Distance  Postcode  ...  SoldYear  SoldMonth  SoldDate
0          2       2.5    3067.0  ...      2016         12         3
1          2       2.5    3067.0  ...      2016          2         4
2          3       2.5    3067.0  ...      2017          3         4
3          3       2.5    3067.0  ...      2017          3         4
4          4       2.5    3067.0  ...      2016          6         4
...      ...       ...       ...  ...       ...        ...       ...
13575      4      16.7    3150.0  ...      2017          8        26
13576      3       6.8    3016.0  ...      2...
2         Abbotsford    h     SP       Yarra       Northern Metropolitan
3         Abbotsford    h     PI       Yarra       Northern Metropolitan
4         Abbotsford    h     VB       Yarra       Northern Metropolitan
...              ...  ...    ...         ...                         ...
13575  Wheelers Hill    h      S         NaN  South-Eastern Metropolitan
13576   Williamstown    h     SP         NaN        Western Metropolitan
13577   Williamstown    h      S         NaN        Western Metropolitan
13578   Williamstown    h     PI         NaN        Western Metropolitan
13579     Yarraville    h     SP         NaN        Western Metropolitan

[13580 rows x 5 columns])])

# **8) Train and Test data split**

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.15)

x.shape

(13580, 17)